// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6MGMzBn8hlZnW7qjM6WO794TUMBOk9GU',
    appId: '1:1019234940342:web:fa4445d4e90b7cc504fd17',
    messagingSenderId: '1019234940342',
    projectId: 'project-exe-33615',
    authDomain: 'project-exe-33615.firebaseapp.com',
    storageBucket: 'project-exe-33615.firebasestorage.app',
    measurementId: 'G-DVH91P9PX6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATiq7OfnoqSe7B0NQ-O2ZJlS1H4m8k6PQ',
    appId: '1:1019234940342:android:700e2a4bb9d8bd4e04fd17',
    messagingSenderId: '1019234940342',
    projectId: 'project-exe-33615',
    storageBucket: 'project-exe-33615.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDssZ35YfnWnl_XfUHriHgivOJlaJvvdQI',
    appId: '1:1019234940342:ios:6e6eac45aa64debe04fd17',
    messagingSenderId: '1019234940342',
    projectId: 'project-exe-33615',
    storageBucket: 'project-exe-33615.firebasestorage.app',
    iosBundleId: 'com.kingserrands.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDssZ35YfnWnl_XfUHriHgivOJlaJvvdQI',
    appId: '1:1019234940342:ios:6e6eac45aa64debe04fd17',
    messagingSenderId: '1019234940342',
    projectId: 'project-exe-33615',
    storageBucket: 'project-exe-33615.firebasestorage.app',
    iosBundleId: 'com.kingserrands.app',
  );
}
